CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY,
  pix_code VARCHAR(255),
  payment_method VARCHAR(32) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  issued_at TIMESTAMP NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
