export type PaymentMethod = "pix" | "credit_card" | "boleto";
export type PaymentStatus = "pending" | "approved" | "failed" | "refunded";

export class Payment {
  constructor(
    public id: string,
    public orderId: string,
    public pixCode: string | null,
    public paymentMethod: PaymentMethod,
    public failureReason: string | null,
    public amount: number,
    public issuedAt: Date,
    public status: PaymentStatus,
    public createdAt: Date,
    public updatedAt: Date,
  ) {}

  static restore(params: {
    id: string;
    orderId: string;
    pixCode: string | null;
    paymentMethod: PaymentMethod;
    failureReason: string | null;
    amount: number;
    issuedAt: Date;
    status: PaymentStatus;
    createdAt: Date;
    updatedAt: Date;
  }): Payment {
    return new Payment(
      params.id,
      params.orderId,
      params.pixCode ?? null,
      params.paymentMethod,
      params.failureReason,
      params.amount,
      params.issuedAt,
      params.status,
      params.createdAt,
      params.updatedAt,
    );
  }

  static create(params: {
    id: string;
    orderId: string;
    pixCode?: string | null;
    paymentMethod: PaymentMethod;
    failureReason?: string | null;
    amount: number;
    issuedAt: Date;
    status: PaymentStatus;
  }): Payment {
    const now = new Date();
    return new Payment(
      crypto.randomUUID(),
      params.orderId,
      Payment.generatePixCode(),
      params.paymentMethod,
      params.failureReason ?? null,
      params.amount,
      params.issuedAt,
      "pending",
      now,
      now,
    );
  }

  approve(): void {
    if (this.status !== "pending") {
      throw new Error(`Cannot approve payment with status ${this.status}`);
    }
    this.status = "approved";
    this.updatedAt = new Date();
  }

  fail(reason: string): void {
    if (this.status !== "pending") {
      throw new Error(`Cannot fail payment with status ${this.status}`);
    }
    this.status = "failed";
    this.failureReason = reason;
    this.updatedAt = new Date();
  }

  setStatus(status: PaymentStatus) {
    this.status = status;
    this.updatedAt = new Date();
  }

  setIssuedAt(issuedAt: Date) {
    this.issuedAt = issuedAt;
    this.updatedAt = new Date();
  }

  setPixCode(pixCode: string | null) {
    this.pixCode = pixCode;
    this.updatedAt = new Date();
  }

  setPaymentMethod(paymentMethod: PaymentMethod) {
    this.paymentMethod = paymentMethod;
    this.updatedAt = new Date();
  }

  setAmount(amount: number) {
    this.amount = amount;
    this.updatedAt = new Date();
  }

  setFailureReason(failureReason: string | null) {
    this.failureReason = failureReason;
    this.updatedAt = new Date();
  }

  //this is used only for testing purposes, since in a real scenario the pix code would be generated by the payment provider
  private static generatePixCode(): string {
    return `PIX-${crypto.randomUUID().toUpperCase()}`;
  }
}
